# 📊 Superstore Data Analysis — Day 5
## Week 1 · Phase 2 — Data Preprocessing · Cleaning & Engineering the Superstore Dataset

> **Goal:** Load the raw Superstore CSV, clean it, engineer new columns, and export `superstore_clean.csv` that Phase 3 dashboards will import.

---

---
## Practice Tasks
---

### T1 — Inspect Raw Data
Load `samplesuperstore.csv` and run the four-line health check: shape, dtypes, null counts, and descriptive stats for the four numeric columns.

In [49]:
import pandas as pd

df = pd.read_csv(r"C:\Users\jarir\Desktop\OJT BCA\project 4.1\data\samplesuperstore.csv")

print("Shape:", df.shape)
print()
print(df.dtypes)
print()
print(df.isnull().sum())
print()
print(df[["Sales", "Quantity", "Discount", "Profit"]].describe())

Shape: (10194, 23)

Row ID               int64
Order ID            object
Order Date          object
Ship Date           object
Ship Mode           object
Customer ID         object
Customer Name       object
Segment             object
Country/Region      object
City                object
State/Province      object
Postal Code         object
Region              object
Product ID          object
Category            object
Sub-Category        object
Product Name        object
Sales              float64
Quantity             int64
Discount           float64
Profit             float64
Shipping Days        int64
Profit Margin %    float64
dtype: object

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State/Province     0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
Shipping Days      0
Profit Margin %    0
dtype: int64

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

### T2 — Check Duplicates
Count fully duplicate rows, then display every row involved in a duplication (both copies) filtered by Order ID.

In [50]:
print("Duplicate rows:", df.duplicated().sum())

dupes = df[df.duplicated(subset=["Order ID"], keep=False)]
print("Rows involved in duplication:", dupes.shape)
dupes.head()

Duplicate rows: 0
Rows involved in duplication: (7601, 23)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Profit Margin %
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-23.75
5,6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078,4,29.00
6,7,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796,4,27.00

### T3 — Date Arithmetic
Convert Order Date and Ship Date from text to datetime, then create a `Shipping Days` column and print average shipping days by Region.

In [51]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"]  = pd.to_datetime(df["Ship Date"])

df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

print(df.groupby("Region")["Shipping Days"].mean().round(1))

Region
Central    4.1
East       3.9
South      4.0
West       3.9
Name: Shipping Days, dtype: float64

### T4 — Profit Margin
Add a `Profit Margin %` column and print the average margin per Sub-Category sorted from lowest to highest.

In [52]:
df["Profit Margin %"] = (df["Profit"] / df["Sales"] * 100).round(2)

print(df.groupby("Sub-Category")["Profit Margin %"]
        .mean()
        .sort_values()
        .head(5)
        .round(1))

Sub-Category
Binders      -19.5
Appliances   -14.9
Tables       -14.0
Bookcases    -13.5
Machines      -6.9
Name: Profit Margin %, dtype: float64

### T5 — Export Clean File
Save the cleaned DataFrame to `data/superstore_clean.csv`, then reload it immediately and verify the shape matches.

In [53]:
df.to_csv(r"C:\Users\jarir\Desktop\OJT BCA\project 4.1\data\samplesuperstore.csv", index=False)

check = pd.read_csv(r"C:\Users\jarir\Desktop\OJT BCA\project 4.1\data\samplesuperstore.csv")
print("Saved shape:", check.shape)

Saved shape: (10194, 23)

---
## End-of-Day Project — Full Preprocessing Pipeline
---

## Step 1 — Imports and File Load
Import pandas and numpy, set the file path, and load the raw CSV into a DataFrame named `df`.

In [54]:
import pandas as pd
import numpy as np

RAW_PATH = r"C:\Users\jarir\Desktop\OJT BCA\project 4.1\data\samplesuperstore.csv"

df = pd.read_csv(RAW_PATH)
print("File loaded successfully.")
print("Shape:", df.shape)

File loaded successfully.
Shape: (10194, 23)

## Step 2 — Data Health Inspection
Run the four-line checklist to understand the dataset size, column types, missing values, and a preview of raw data before making any changes.

**Observations to fill in after running:**
- `Order Date` and `Ship Date` are dtype `object`, not datetime — need conversion
- No missing values found in any column
- Sales and Profit have wide ranges — worth inspecting for outliers

In [55]:
print("=== Shape ===")
print(df.shape)

print("\n=== Data Types ===")
print(df.dtypes)

print("\n=== Missing Values ===")
print(df.isnull().sum())

print("\n=== First 3 Rows ===")
df.head(3)

=== Shape ===
(10194, 23)

=== Data Types ===
Row ID               int64
Order ID            object
Order Date          object
Ship Date           object
Ship Mode           object
Customer ID         object
Customer Name       object
Segment             object
Country/Region      object
City                object
State/Province      object
Postal Code         object
Region              object
Product ID          object
Category            object
Sub-Category        object
Product Name        object
Sales              float64
Quantity             int64
Discount           float64
Profit             float64
Shipping Days        int64
Profit Margin %    float64
dtype: object

=== Missing Values ===
Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State/Province     0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
Shipping Days      0
Profit Margin %    0
dtype: int64

=== First 3 Rows ===

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Profit Margin %
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4,36.25

## Step 3 — Check and Remove Duplicates
Count fully duplicate rows, display them for inspection, then drop them. Print the shape before and after so we can see how many rows were removed.

In [56]:
print("Shape BEFORE removing duplicates:", df.shape)
print("Duplicate rows found:", df.duplicated().sum())

# Display all rows involved in duplication (both copies)
dupes = df[df.duplicated(subset=["Order ID"], keep=False)]
print("\nRows involved in duplication:")
print(dupes.shape)
dupes.head(10)

Shape BEFORE removing duplicates: (10194, 23)
Duplicate rows found: 0

Rows involved in duplication:
(7601, 23)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Profit Margin %
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-23.75
5,6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078,4,29.00
6,7,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796,4,27.00
8,9,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2,0.0,274.4910,4,45.00
9,10,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,OFF-FA-10001883,Office Supplies,Fasteners,"Alliance Super-Size Bands, Assorted Sizes",31.120,4,0.0,0.3112,4,1.00
10,11,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,OFF-PA-10000955,Office Supplies,Paper,Southworth 25% Cotton Granite Paper & Envelopes,6.540,1,0.0,3.0084,4,46.00
12,13,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.960,4,0.0,204.1092,4,27.00
13,14,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,TEC-PH-10004977,Technology,Phones,GE 30524EE4,391.980,2,0.0,113.6742,4,29.00

In [57]:
# Drop fully duplicate rows
df.drop_duplicates(inplace=True)

print("Shape AFTER removing duplicates:", df.shape)

Shape AFTER removing duplicates: (10194, 23)

## Step 4 — Convert Date Columns
Convert `Order Date` and `Ship Date` from text (object) to datetime64 so we can do date arithmetic in Step 5. Confirm the conversion by printing dtypes.

In [58]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"]  = pd.to_datetime(df["Ship Date"])

# Confirm both columns are now datetime64
print(df[["Order Date", "Ship Date"]].dtypes)

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

## Step 5 — Engineer: Shipping Days
Subtract Order Date from Ship Date and extract the integer number of days using `.dt.days`. This measures how long each delivery actually took.

In [59]:
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

print("Shipping Days — min / max / mean:")
print(f"  Min : {df['Shipping Days'].min()} days")
print(f"  Max : {df['Shipping Days'].max()} days")
print(f"  Mean: {df['Shipping Days'].mean().round(1)} days")

Shipping Days — min / max / mean:
  Min : 0 days
  Max : 11 days
  Mean: 4.0 days

## Step 6 — Engineer: Order Year
Extract the year from `Order Date` using `.dt.year` and store it in a new column. This is used for year-over-year comparison charts in Phase 3.

In [60]:
df["Order Year"] = df["Order Date"].dt.year

print("Unique years in the dataset:")
print(sorted(df["Order Year"].unique()))

Unique years in the dataset:
[np.int32(2023), np.int32(2024), np.int32(2025), np.int32(2026)]

## Step 7 — Engineer: Profit Margin %
Calculate profit as a percentage of sales. Negative values mean the company lost money on that sale — usually caused by high discounts. This column feeds directly into Phase 3 profitability charts.

In [61]:
df["Profit Margin %"] = (df["Profit"] / df["Sales"] * 100).round(2)

print("Bottom 5 Sub-Categories by average Profit Margin %:")
print(
    df.groupby("Sub-Category")["Profit Margin %"]
      .mean()
      .sort_values()
      .head(5)
      .round(1)
)

Bottom 5 Sub-Categories by average Profit Margin %:
Sub-Category
Binders      -19.5
Appliances   -14.9
Tables       -14.0
Bookcases    -13.5
Machines      -6.9
Name: Profit Margin %, dtype: float64

## Step 8 — Rename Columns for Clean Code
Rename columns that have spaces or inconsistent capitalisation so they are easier to reference in Phase 3 code without needing quotes around every column name.

In [62]:
df = df.rename(columns={
    "Sub-Category":  "sub_category",
    "Ship Mode":     "ship_mode",
    "Customer Name": "customer_name",
})

print("Updated column names:")
print(df.columns.tolist())

Updated column names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'ship_mode', 'Customer ID', 'customer_name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category', 'sub_category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Days', 'Profit Margin %', 'Order Year']

## Step 9 — Final Inspection and Export
Print a summary of the cleaned DataFrame — final shape, all column names, and stats on the three new engineered columns. Then save to `superstore_clean.csv`, reload, and confirm the shape matches.

In [63]:
print("=== Final Shape ===")
print(df.shape)

print("\n=== All Columns ===")
print(df.columns.tolist())

print("\n=== Engineered Columns Summary ===")
print(df[["Shipping Days", "Order Year", "Profit Margin %"]].describe().round(2))

=== Final Shape ===
(10194, 24)

=== All Columns ===
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'ship_mode', 'Customer ID', 'customer_name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category', 'sub_category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Days', 'Profit Margin %', 'Order Year']

=== Engineered Columns Summary ===
       Shipping Days  Order Year  Profit Margin %
count       10194.00    10194.00         10194.00
mean            3.96     2024.72            12.22
std             1.74        1.13            46.49
min             0.00     2023.00          -275.00
25%             3.00     2024.00             7.50
50%             4.00     2025.00            27.00
75%             5.00     2026.00            36.25
max            11.00     2026.00            50.00

In [64]:
# Export
df.to_csv(r"C:\Users\jarir\Desktop\OJT BCA\project 4.1\data\superstore_clean.csv", index=False)

# Verify
check = pd.read_csv(r"C:\Users\jarir\Desktop\OJT BCA\project 4.1\data\superstore_clean.csv")
print("Saved shape :", check.shape)
print("Cleaned file confirmed ✅")

Saved shape : (10194, 24)
Cleaned file confirmed ✅

---

**DBI Skill Park · Superstore Data Analysis · Week 1 · Day 5 · Phase 2 — Data Preprocessing**